apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customjobs.custom.example.com
spec:
  group: custom.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string
            status:
              type: object
              properties:
                bar:
                  type: string
  scope: Namespaced
  names:
    plural: customjobs
    singular: customjob
    kind: CustomJob
    shortNames:
      - cj
